version: '3.8'

services:
  # Next.js Application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/courier-connect
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - courier-network

  # MongoDB Database
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - courier-network
    environment:
      - MONGO_INITDB_DATABASE=courier-connect

volumes:
  mongo-data:

networks:
  courier-network:
    driver: bridge
