name: Feature Request ✨
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We love new ideas! Thanks for suggesting a feature. 🚀
  
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this feature work?
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other solutions have you thought about?
  
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any mockups, examples, or other context?
